"""empty message

Revision ID: 196d2b606a20
Revises: 31cfb7daf1f9
Create Date: 2024-02-27 18:23:40.298372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196d2b606a20'
down_revision = '31cfb7daf1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
