"""empty message

Revision ID: 4e27961a3f26
Revises: cd95022b4573
Create Date: 2024-03-04 23:07:55.583204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e27961a3f26'
down_revision = 'cd95022b4573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, foreign_key='user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
